# Generated by Django 3.0.5 on 2020-07-05 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200704_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_slot_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 7, 26, 10, 420020, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_slot_start',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 7, 26, 13, 109106, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(default='__REGULAR-USER__', max_length=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.ManyToManyField(to='api.Status_Choices'),
        ),
    ]
