# Generated by Django 3.0.5 on 2020-07-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200705_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Status_Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status_field_choice', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Status_Choices',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ManyToManyField(to='api.Booking_Status_Field'),
        ),
    ]
